### ISSUE TITLE
resolve apparently conflicting new tags for CormierBLPW and R5_SALS

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/TO_DO#42]
These pairs of tags appear to conflict, but might simply be transfers between projects.
If they are real conflicts, the new version of the tag finder will flag ambiguous detections,
but the old version will only detect the first tag listed.  Owners of the newer 
tag in the conflict should be asked to defer deployment if possible.

Please check off items and add an M or C before the entry to indicate "move" or "conflict":
- [ ] BerriganIPSP#50:37.3 conflicts with new tag for CormierBLPW
- [ ] Protandry#53:37.3 conflicts with new tag for CormierBLPW
- [ ] BerriganIPSP#62:37.3 conflicts with new tag for CormierBLPW
- [ ] QC-Thrush#74:10.7 conflicts with new tag for R5_SALS
- [ ] QC-Thrush#79:10.7 conflicts with new tag for R5_SALS
- [ ] NolWS#67:10.7 conflicts with new tag for R5_SALS
- [ ] NolWS#64:10.7 conflicts with new tag for R5_SALS

**Comment by StuMackenzie** [comment]
Are these all new registrations that you have to process?

**Comment by jbrzusto** [comment]
They've been processed, but not pushed to motus yet.

On Thu, Sep 1, 2016, at 12:39, StuMackenzie wrote:
> Are these all new registrations that you have to process?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jbrzusto/TO_DO/issues/42#issuecomment-244119764


-- 
#-----------------------------------
#  John Brzustowski
#  Wolfville, NS  Canada

**Comment by StuMackenzie** [comment]
OK - we haven't done anything with these, so I think it's best to label them as conflicts for now.

**Comment by jbrzusto** [comment]
if not a mistake, now handled by ambiguity code in the tag finder
